#!/bin/bash
#
# init script for the Ethernet Bridge filter tables
#
# Written by Dag Wieers <dag@wieers.com>
# Modified by Rok Papez <rok.papez@arnes.si>
#             Bart De Schuymer <bdschuym@pandora.be>
#
# chkconfig: - 15 85
# description: Ethernet Bridge filtering tables
#
# config: /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables         (text)
#         /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables.<table> (binary)

source /etc/init.d/functions
source /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

[ -x /home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables ] || exit 1
[ -x /home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables-save ] || exit 1
[ -x /home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables-restore ] || exit 1

RETVAL=0
prog="ebtables"
desc="Ethernet bridge filtering"
umask 0077

#default configuration
EBTABLES_TEXT_FORMAT="yes"
EBTABLES_BINARY_FORMAT="yes"
EBTABLES_MODULES_UNLOAD="yes"
EBTABLES_SAVE_ON_STOP="no"
EBTABLES_SAVE_ON_RESTART="no"
EBTABLES_SAVE_COUNTER="no"

config=/home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/$prog-config
[ -f "$config" ] && . "$config"

start() {
	echo -n $"Starting $desc ($prog): "
	if [ "$EBTABLES_BINARY_FORMAT" = "yes" ]; then
		for table in $(ls /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables.* | sed s/.*ebtables.//); do
			/home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables -t $table --atomic-file /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables.$table --atomic-commit || RETVAL=1
		done
	else
		/home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables-restore < /etc/sysconfig/ebtables || RETVAL=1
	fi

	if [ $RETVAL -eq 0 ]; then
		success "$prog startup"
		rm -f /var/lock/subsys/$prog
	else
		failure "$prog startup"
	fi
	echo
}

stop() {
	echo -n $"Stopping $desc ($prog): "
	for table in $(grep -E '^ebtable_' /proc/modules | cut -f1 -d' ' | sed s/ebtable_//); do
		/home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables -t $table --init-table || RETVAL=1
	done

	if [ "$EBTABLES_MODULES_UNLOAD" = "yes" ]; then
		for mod in $(grep -E '^(ebt|ebtable)_' /proc/modules | cut -f1 -d' ') ebtables; do
			rmmod $mod 2> /dev/null
		done
	fi

	if [ $RETVAL -eq 0 ]; then
		success "$prog shutdown"
		rm -f /var/lock/subsys/$prog
	else
		failure "$prog shutdown"
	fi
	echo
}

restart() {
	stop
	start
}

save() {
	echo -n $"Saving $desc ($prog): "
	if [ "$EBTABLES_TEXT_FORMAT" = "yes" ]; then
		if [ -e /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables ]; then
			chmod 0600 /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables
			mv -f /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables.save
		fi
		/home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables-save > /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables || RETVAL=1
	fi
	if [ "$EBTABLES_BINARY_FORMAT" = "yes" ]; then
		rm -f /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables.*.save
		for oldtable in $(ls /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables.*); do
			if [ "$oldtable" !=  /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables.save ]; then
				chmod 0600 $oldtable
				mv -f $oldtable $oldtable.save
			fi
		done
		for table in $(grep -E '^ebtable_' /proc/modules | cut -f1 -d' ' | sed s/ebtable_//); do
			/home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables -t $table --atomic-file /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables.$table --atomic-save || RETVAL=1
			if [ "$EBTABLES_SAVE_COUNTER" = "no" ]; then
				/home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables -t $table --atomic-file /home/release/release.dap2230/runtime/v102/rootfs/etc/sysconfig/ebtables.$table -Z || RETVAL=1
			fi
		done
	fi

	if [ $RETVAL -eq 0 ]; then
		success "$prog saved"
	else
		failure "$prog saved"
	fi
	echo
}

case "$1" in
  start)
	start
	;;
  stop)
	[ "$IPTABLES_SAVE_ON_STOP" = "yes" ] && save
	stop
	;;
  restart|reload)
	[ "$IPTABLES_SAVE_ON_RESTART" = "yes" ] && save
	restart
	;;
  condrestart)
	[ -e /var/lock/subsys/$prog ] && restart
	RETVAL=$?
	;;
  save)
	save
	;;
  status)
	/home/release/release.dap2230/runtime/v102/rootfs/sbin/ebtables-save
	RETVAL=$?
	;;
  *)
	echo $"Usage $0 {start|stop|restart|condrestart|save|status}"
	RETVAL=1
esac

exit $RETVAL
