. ../../../.config

echo "  <?"
echo "  /* vi: set sw=4 ts=4: */"
echo "  require(\"/etc/templates/troot.php\");"
echo "  "
echo "  \$klog_pid=\"/var/run/klogd.pid\";"
echo "  \$lanif=query(\"/runtime/layout/lanif\");"
echo "  \$wanif=query(\"/runtime/wan/inf:1/interface\");"
echo "  if (\$wanif==\"\") { \$wanif=query(\"/runtime/layout/wanif\"); }"
echo "  /*syslogd_2007_01_23 , Jordan start */"
echo "  \$loglevel=query(\"/security/log/loglevel\");"
echo "  \$first_init=query(\"/runtime/log/first_init\");"
echo "  \$First_init_RemoLog=query(\"/runtime/log/Remote_log_init\");"
echo "  \$fw_ver=query(\"/runtime/sys/info/firmwareversion\");"
echo "  /*syslogd_2007_01_23 , Jordan end*/"
echo "  \$remoteInfo=query(\"/security/log/remoteInfo\");/*RemoteLog_2007_02_15, Jordan */"
echo "  \$smtpInfo=query(\"/security/log/smtpInfo\");/*smtp_2007_02_16, Jordan*/"
echo "  if (\$klogd_only != 1)"
echo "  {"
echo "  	\$syslog_pid=\"/var/run/syslogd.pid\";"
echo "  "
echo "  	echo \"if [ -f \".\$syslog_pid.\" ]; then\n\";"
echo "  	echo \"	PID=\`cat \".\$syslog_pid.\"\`\n\";"
echo "  	echo \"	if [ \$PID != 0 ]; then\n\";"
echo "  	echo \"		kill \$PID > /dev/console 2>&1\n\";"
echo "  	echo \"	fi\n\";"
echo "  	echo \"	rm -f \".\$syslog_pid.\"\n\";"
echo "  	echo \"fi\n\";"
echo "  "
echo "  /*schedule_smtp.2008_03_26.allen*/"
echo "  	\$timer_email_pid=\"/var/run/timer_email.pid\";"
echo "  	"
echo "  	echo \"if [ -f \".\$timer_email_pid.\" ]; then\n\";"
echo "  	echo \"	PID=\`cat \".\$timer_email_pid.\"\`\n\";"
echo "  	echo \"	if [ \$PID != 0 ]; then\n\";"
echo "  	echo \"		kill \$PID > /dev/console 2>&1\n\";"
echo "  	echo \"	fi\n\";"
echo "  	echo \"	rm -f \".\$timer_email_pid.\"\n\";"
echo "  	echo \"fi\n\";"
echo "  	"
if [ "$ELBOX_PROGS_GPL_EMAILCLIENT" == "y" ]; then
echo "	\$smtpsindex=query(\"/sys/log/smtpindex\");"
echo "	\$smtps=query(\"/sys/log/smtp/index:\".\$smtpsindex.\"/mailserver\");"
echo "	\$fromemail=query(\"/sys/log/smtp/index:\".\$smtpsindex.\"/fromemail\");"
echo "	\$toemail=query(\"/sys/log/smtp/index:\".\$smtpsindex.\"/toemail\");"
else
echo "  	\$smtps=query(\"/sys/log/mailserver\");"
echo "  	\$fromemail=query(\"/sys/log/fromemail\");/*syslogd_2008_03_03.allen*/"
echo "  	\$toemail=query(\"/sys/log/toemail\");/*syslogd_2008_03_03.allen*/"
fi
echo "  	\$hostname=query(\"/sys/hostname\");"
echo "  	\$logserver=query(\"/sys/log/logserver\");/*syslogd_2007_01_23 , Jordan */"
echo "  	\$eulogserver=query(\"/sys/log/eulogserver\");/*syslogd_2014_11_12 , Ken*/"
echo "  	\$opts=\"\";"
echo "  /*schedule_smtp.2008_03_26.allen*/"
echo "  	\$timer_opts=\"\";"
echo "  	\$timer=query(\"/sys/log/timemail\");"
echo "  /* auth ESMTP_2008_04_29,allen */"
echo "  //	\$port = \"25\" ;"
if [ "$ELBOX_PROGS_GPL_EMAILCLIENT" == "y" ]; then
echo "  	\$password = query(\"/sys/log/smtp/index:\".\$smtpsindex.\"/pass1\");"
echo "  	\$username = query(\"/sys/log/smtp/index:\".\$smtpsindex.\"/username\");"
else
echo "  	\$password = query(\"/sys/log/pass1\");"
echo "  	\$username = query(\"/sys/log/username\");"
fi
echo "  	"
echo "  	"
echo "  	anchor(\"/security/log\");"
echo "  	if (query(\"systeminfo\")==1)		{ \$opts=\$opts.\" -F sysact\"; }"
echo "  	if (query(\"debuginfo\")==1)		{ \$opts=\$opts.\" -F debug\"; }"
echo "  	if (query(\"attackinfo\")==1)		{ \$opts=\$opts.\" -F attack\"; }"
echo "  	if (query(\"droppacketinfo\")==1)	{ \$opts=\$opts.\" -F drop\"; }"
echo "  	if (query(\"noticeinfo\")==1)		{ \$opts=\$opts.\" -F notice\"; }"
echo "  /*syslogd_2007_02_02 , Jordan start */"
echo "  	if (query(\"WirelessInfo\")==1)		{ \$opts=\$opts.\" -F wireless\"; }"
echo "  	if (query(\"apsystemInfo\")==1)		{ \$opts=\$opts.\" -F apsysact\"; }"
echo "  	if (query(\"apnoticeInfo\")==1)		{ \$opts=\$opts.\" -F apnotice\"; }"
echo "          if (\$loglevel != \"\") { \$opts=\$opts.\" -l \".\$loglevel; }	/*klogd_2007_01_30 , Jordan */"
echo "  /*syslogd_2007_02_02 , Jordan end*/    "
echo "  /*syslogd_2007_01_23 , Jordan start */"
echo "  	if (\$remoteInfo == 1)/*RemoteLog_2007_02_15, Jordan */"
echo "  	{"
echo "  		if (\$first_init != 1)/* syslog_2007_04_09 , Jordan */"
echo "  		/*if (\$withremotelog == 1)*//*syslogd_2007_02_09*//* syslog_2007_04_09 , Jordan*/"
echo "  		{"
echo "  			if (\$logserver != \"\") "
echo "  			{ "
echo "  				\$opts=\$opts.\"  -R \".\$logserver; "
echo "        				if(\$logport != \"\")"
echo "        		 		{"
echo "          		 		\$opts=\$opts.\":\".\$logport;"
echo "        			 	}"
echo "      			}"
echo "				if (\$eulogserver != \"\")  /*EU directive server log*//*syslogd_2014_11_12 , Ken*/"
echo "				{"
echo " 					\$opts=\$opts.\"  -F eulog\";"
echo "					\$opts=\$opts.\"  -E \".\$eulogserver;"
echo "				}"
echo "  		}"
echo "  	}"
echo "  /*syslogd_2007_01_23 , Jordan end*/"
echo "  	if (\$smtpInfo == 1)/*smtp_2007_02_16, Jordan*/"
echo "  	{"
echo "  		/*syslogd_2008_03_03.allen*/"
echo "  		if(\$toemail == \"\")"
echo "  		{"
echo "  			\$toemail=\$fromemail;"
echo "  		}"
echo "  		if (\$smtps != \"\" && \$fromemail != \"\")"
echo "  	{"
echo "		//\$opts=\$opts.\" -t /var/log/messages\"."
echo "		//		\" -m -S \\\"\".\$smtps.\"\\\" -a \\\"\".\$fromemail.\"\\\" -r \\\"\".\$toemail.\"\\\" -H \\\"\".\$hostname.\"\\\"\";"
echo "		\$opts=\$opts.\" -t /var/log/messages\"."
echo "				\" -m -S \\\"\".\$smtps.\"\\\" -a \\\"\".\$fromemail.\"\\\" -r \\\"\".\$toemail.\"\\\" -H \\\"\".\$hostname.\"\\\" -P \\\"\".\$password.\"\\\" -u \\\"\".\$username.\"\\\"\";"
echo "		"
echo "		/*schedule_smtp.2008_03_26.allen*/"
echo "		\$timer_opts=\" -t /var/log/smtpmsg\"."
echo "				\" -S \\\"\".\$smtps.\"\\\" -a \\\"\".\$fromemail.\"\\\" -r \\\"\".\$toemail.\"\\\" -H \\\"\".\$hostname."
echo "				\"\\\" -T \\\"\".\$timer.\"\\\" -P \\\"\".\$password.\"\\\" -u \\\"\".\$username.\"\\\"\";"
echo "	}"
echo "  	}"
echo "  	if (\$first_init == 1) { \$opts=\$opts.\" -b \".\$fw_ver; }	/*syslog_2007_02_16 , Jordan*/"
echo "  	if (\$First_init_RemoLog == 1) { \$opts=\$opts.\" -i\"; }"
echo "  	if (\$opts != \"\")"
echo "  	{"
echo "  		echo \"syslogd \".\$opts.\" &\n\";"
echo "  		echo \"echo \$! > \".\$syslog_pid.\"\n\";"
echo "  	}"
echo "  	/*schedule_smtp.2008_03_26.allen*/"
echo "  	if (\$timer_opts != \"\")"
echo "  	{"
echo "  		echo \"schedule_smtp\".\$timer_opts.\" &\n\";"
echo "  		echo \"echo \$! > \".\$timer_email_pid.\"\n\";	"
echo "  	}"
echo "  	"
echo "  }"
echo "  "
echo "  echo \"if [ -f \".\$klog_pid.\" ]; then\n\";"
echo "  echo \"	PID=\`cat \".\$klog_pid.\"\`\n\";"
echo "  echo \"	if [ \$PID != 0 ]; then\n\";"
echo "  echo \"		kill \$PID > /dev/console 2>&1\n\";"
echo "  echo \"	fi\n\";"
echo "  echo \"	rm -f \".\$klog_pid.\"\n\";"
echo "  echo \"fi\n\";"
echo "  /*klogd_2007_01_30 , Jordan start */"
echo "  \$opts=\"\";"
echo "  /*syslog_2007_02_16 , Jordan marked*/"
echo "  /*if (\$first_init == 1) { \$opts=\$opts.\" -b \".\$fw_ver; }*//*ap71_syslogd_20061125*//*Added by Erick*/"
echo "  "
echo "  if (\$loglevel != \"\")"
echo "  {echo \"klogd -c \".\$loglevel.\" \".\$opts.\" &\n\";}"
echo "  else"
echo "  {echo \"klogd -c 5 \".\$opts.\" &\n\";}"
echo "  echo \"echo \$! > \".\$klog_pid.\"\n\";"
echo "  echo \"rgdb -s /security/log/first_init 0\n\";"
echo "  /*"
echo "  echo \"klogd -l \".\$lanif.\" -w \".\$wanif.\" &\n\";"
echo "  echo \"echo \$! > \".\$klog_pid.\"\n\";"
echo "  */"
echo "  /*klogd_2007_01_30 , Jordan end*/"
echo "  ?>"

