<?
$model2590 = fread("/etc/config/model_ver");
if($model2590=="it_is_2590_ip_v6_version")
{
	set("/runtime/web/display/ipv6","1");
	set("/runtime/web/display/sys/hostname","DAP-2590");
	set("/runtime/web/display/igmp","0");
	set("/runtime/web/display/rts","0");
	set("/runtime/web/display/frag","0");
	set("/runtime/web/display/utilization","1");
	set("/runtime/web/display/nap_server","0");
	set("/runtime/web/display/backup_radius_server","1");
	set("/runtime/web/display/accounting_server","1");
	set("/runtime/web/display/backup_accounting_server","1");
	set("/runtime/web/display/status/ap_status","1");
	set("/runtime/web/display/status/cpu","1");
	set("/runtime/web/display/status/memory","1");
	set("/runtime/web/display/statistics/received","1");
	set("/runtime/web/display/statistics/len","1");
	set("/runtime/web/display/log/email","1");
	set("/runtime/web/display/snmp/trap","1");
	set("/runtime/web/display/ping_control","1");
	set("/runtime/web/display/stat_wl","1");
	set("/runtime/web/display/priority","1");
	set("/runtime/web/display/mssid_index4","0");
	set("/runtime/web/display/language","0");
	set("/runtime/web/display/schedule_wireless","0");
	set("/runtime/web/display/ap_array","1");
	set("/runtime/web/display/url_redir","0");
	set("/runtime/web/display/arp_spf","0");
	set("/runtime/web/display/wisp","0");
	//set("/runtime/web/display/wlmode_support_n_only","1");
	set("/runtime/web/display/mssid_support_sharedkey","0");
	set("/runtime/web/display/multi_dhcp","1");
	set("/runtime/web/display/ack_timeout_range","0");
	set("/runtime/web/display/802.1x_support", "1");
	set("/runtime/web/display/local_radius_server", "1");
	set("/runtime/web/display/autorekey","0");
	set("/runtime/web/display/aclupdnload","0");
}
else
{
	set("/runtime/web/display/sys/hostname","DAP-2590");
	set("/runtime/web/display/igmp","1");
	set("/runtime/web/display/rts","0");
	set("/runtime/web/display/frag","0");
	set("/runtime/web/display/utilization","1");
	set("/runtime/web/display/nap_server","1");
	set("/runtime/web/display/backup_radius_server","1");
	set("/runtime/web/display/accounting_server","1");
	set("/runtime/web/display/backup_accounting_server","1");
	set("/runtime/web/display/status/ap_status","1");
	set("/runtime/web/display/status/cpu","1");
	set("/runtime/web/display/status/memory","1");
	set("/runtime/web/display/statistics/received","1");
	set("/runtime/web/display/statistics/len","1");
	set("/runtime/web/display/log/email","1");
	set("/runtime/web/display/snmp/trap","1");
	set("/runtime/web/display/ping_control","1");
	set("/runtime/web/display/stat_wl","1");
	set("/runtime/web/display/priority","1");
	set("/runtime/web/display/mssid_index4","0");
	set("/runtime/web/display/language","1");
	set("/runtime/web/display/schedule_wireless","0");
	set("/runtime/web/display/ap_array","1");
	set("/runtime/web/display/url_redir","0");
	set("/runtime/web/display/arp_spf","0");
	set("/runtime/web/display/wisp","0");
	//set("/runtime/web/display/wlmode_support_n_only","1");
	set("/runtime/web/display/mssid_support_sharedkey","0");
	set("/runtime/web/display/multi_dhcp","1");
	set("/runtime/web/display/ack_timeout_range","0");
	set("/runtime/web/display/802.1x_support", "1");
	set("/runtime/web/display/local_radius_server", "1");
	set("/runtime/web/display/autorekey","0");
	set("/runtime/web/display/aclupdnload","0");
}
?>
