/*$model2690 = fread("/etc/config/model_ver");
if(model2695=="it_is_2590_ip_v6_version")
{
	set("/runtime/web/display/mssid_index4","1");
}
else
{
	set("/runtime/web/display/mssid_index4","0");
}*/
set("/runtime/web/display/sys/hostname","DAP-3662");
set("/runtime/web/display/status/cpu","1");
set("/runtime/web/display/status/memory","1");
set("/runtime/web/display/status/ap_status","1");
set("/runtime/web/display/statistics/received","0");
set("/runtime/web/display/statistics/len","0");
set("/runtime/web/display/mssid_index0","0");
set("/runtime/web/display/mssid_index4","0");
set("/runtime/web/display/stat_wl","1");
set("/runtime/web/display/802.1x_support","1");
set("/runtime/web/display/backup_radius_server","1");
set("/runtime/web/display/accounting_server","1");
set("/runtime/web/display/backup_accounting_server","1");
set("/runtime/web/display/ack_timeout_range","0");
set("/runtime/web/display/mssid_support_sharedkey","0");
set("/runtime/web/display/schedule_wireless","0");
set("/runtime/web/display/wlmode_support_n_only","1");
set("/runtime/web/display/multi_dhcp","1");
set("/runtime/web/display/outdoor","1");
if(query("/runtime/layout/countrycode") == "376")
{
	set("/wlan/inf:2/ap_mode","");
	set("/wlan/inf:2/enable","");
}
