<?
/* vi: set sw=4 ts=4: */
$MY_NAME      = "help";
$MY_MSG_FILE  = $MY_NAME.".php";

require("/www/model/__html_head.php");

$help_page = query("/runtime/web/help_page");
$cap_v1 = query("/runtime/web/display/cap_v1");
echo $G_TAG_SCRIPT_START."\n";
?>
function init()
{
	location.href="help.php#<?=$help_page?>";
}

<?
echo $G_TAG_SCRIPT_END."\n";
?>


<body onload="init();" <?=$G_BODY_ATTR?>>
<form name="frm" id="frm">
<center>
<table <?=$G_MAIN_TABLE_ATTR?>>
<tr valign="middle" align="center">
	<td>
		
		
		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_bsc?></td>
			</tr>	
		</table>
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td class="help_title_td"><?=$title_bsc_wlan?><a name="bsc_wlan"></a></td>
			</tr>
			<tr>
				<td><?=$bsc_wlan_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$bsc_wireless_band?></b><br>
					<?=$bsc_wireless_band_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_mode?></b><br>
					<?=$bsc_mode_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_network_name?></b><br>
					<?=$bsc_network_name_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_ssid_visibility?></b><br>
					<?=$bsc_ssid_visibility_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_auto_channel?></b><br>
					<?=$bsc_auto_channel_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_channel?></b><br>
					<?=$bsc_channel_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_channel_width?></b><br>
					<?=$bsc_channel_width_msg?>	
				</td>	
			</tr>	
<?if($cap_v1 != 1){echo "<!--";}?>
			<tr>
				<td>
					<b><?=$bsc_captive_profile?></b><br>
					<?=$bsc_captive_profile_msg?>
				</td>
			</tr>
<?if($cap_v1 != 1){echo "-->";}?>
			<tr>
				<td>
					<b><?=$bsc_authentication?></b><br>
					<?=$bsc_authentication_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_open_sys?></b><br>
					<?=$bsc_open_sys_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_shared_key?></b><br>
					<?=$bsc_shared_key_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_personal_type?></b><br>
					<?=$bsc_personal_type_msg?>	
				</td>	
			</tr>
			<tr>
                <td>
                    <b><?=$bsc_periodrical_change_key?></b><br>
                    <?=$bsc_periodrical_change_key_msg?>
                </td>
            </tr>	
			<tr>
				<td>
					<b><?=$bsc_enterprise_type?></b><br>
					<?=$bsc_enterprise_type_msg?>	
				</td>	
			</tr>
			<tr>
                <td>
                    <b><?=$bsc_8021x_type?></b><br>
                    <?=$bsc_8021x_type_msg?>
                </td>
            </tr>	
			<tr>
				<td>
					<b><?=$bsc_network_access?></b><br>
					<?=$bsc_network_access_msg?>	
				</td>	
			</tr>				
			<tr>
				<td class="help_title_td"><?=$title_bsc_lan?><a name="bsc_lan"></a></td>
			</tr>
			<tr>
				<td><?=$title_bsc_lan_msg?></td>
			</tr>		
			<tr>
				<td>
					<b><?=$bsc_get_ip_from?></b><br>
					<?=$bsc_get_ip_from_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_ip_address?></b><br>
					<?=$bsc_ip_address_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_submask?></b><br>
					<?=$bsc_submask_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$bsc_gateway?></b><br>
					<?=$bsc_gateway_msg?>	
				</td>	
			</tr>									
			<tr>
				<td>
					<b><?=$bsc_dns?></b><br>
					<?=$bsc_dns_msg?>
				</td>
			</tr>
<? if(query("/runtime/web/display/ipv6") != 1) {echo "<!--";}?>
            <tr>
                <td class="help_title_td"><?=$title_bsc_ipv6?><a name="bsc_ipv6"></a></td>
            </tr>
            <tr>
                <td><?=$title_bsc_ipv6_msg?></td>
            </tr>
            <tr>
                <td>
                    <b><?=$bsc_get_ip_from?></b><br>
                    <?=$bsc_get_ip_from_msg_ipv6?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$bsc_ip_address?></b><br>
                    <?=$bsc_ip_address_msg_ipv6?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$bsc_prefix?></b><br>
                    <?=$bsc_prefix_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$bsc_gateway?></b><br>
                    <?=$bsc_gateway_ipv6_msg?>
                </td>
            </tr>
<? if(query("/runtime/web/display/ipv6") != 1) {echo "-->";}?>
		</table>	
		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_adv?></td>
			</tr>	
		</table>		
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td class="help_title_td"><?=$title_adv_per?><a name="adv_perf"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_per_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_wireless?></b><br>
					<?=$adv_wireless_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_wireless_mode?></b><br>
					<?=$adv_wireless_mode_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_date_rate?></b><br>
					<?=$adv_date_rate_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_beacon?></b><br>
					<?=$adv_beacon_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_dtim?></b><br>
					<?=$adv_dtim_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_transmit_power?></b><br>
					<?=$adv_transmit_power_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_wmm?></b><br>
					<?=$adv_wmm_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_ack_timeout?></b><br>
					<?=$adv_ack_timeout_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_short_gi?></b><br>
					<?=$adv_short_gi_msg?>	
				</td>	
			</tr>
<? if(query("/runtime/web/display/igmp") =="0")  {echo "<!--";} ?>
			<tr>
				<td>
					<b><?=$adv_igmp?></b><br>
					<?=$adv_igmp_msg?><br>	
					<?=$adv_igmp_msg2?>
				</td>	
			</tr>
<? if(query("/runtime/web/display/igmp") =="0")  {echo "-->";} ?>
			<tr>
                <td>
                    <b><?=$adv_mcast_rate?></b><br>
                    <?=$adv_mcast_rate_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_mcast_control?></b><br>
                    <?=$adv_mcast_control_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$adv_bandwidth_rate?></b><br>
                    <?=$adv_bandwidth_rate_msg?>
                </td>
            </tr>
	    <tr>
                <td>
                    <b><?=$adv_coexistence?></b><br>
                    <?=$adv_coexistence_msg?>
                </td>
            </tr>
<? if(query("/runtime/web/display/multi2uni") !="1")  {echo "<!--";} ?>
			<tr>
				<td>
					<b><?=$adv_m2u?></b><br>
					<?=$adv_m2u_msg?>
				</td>
			</tr>
<? if(query("/runtime/web/display/multi2uni") !="1")  {echo "-->";} ?>

			<tr>
				<td class="help_title_td"><?=$title_adv_resource?><a name="adv_resource"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_resource_msg?></td>
			</tr>
<? if(query("/wlan/inf:2/ap_mode") =="")  {echo "<!--";} ?>
			<tr>
				<td>
					<b><?=$adv_5g_preferred?></b><br>
					<?=$adv_5g_preferred_msg?>
				</td>
			</tr>
			<tr>
                <td>
                    <b><?=$adv_5g_preferred_age?></b><br>
                    <?=$adv_5g_preferred_age_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_5g_preferred_diff?></b><br>
                    <?=$adv_5g_preferred_diff_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_5g_preferred_ref?></b><br>
                    <?=$adv_5g_preferred_ref_msg?>
                </td>
            </tr>
<? if(query("/wlan/inf:2/ap_mode") =="")  {echo "-->";} ?>
			<!--tr>
                <td>
                    <b><?=$adv_5g_preferred_rssi?></b><br>
                    <?=$adv_5g_preferred_rssi_msg?>
                </td>
            </tr-->
			 <tr>
                <td>
                    <b><?=$adv_connection_limit?></b><br>
                    <?=$adv_connection_limit_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_user_limit?></b><br>
                    <?=$adv_user_limit_msg?>
                </td>
            </tr>
<? if(query("/runtime/web/display/agingout")!="1") {echo "<!--";}?>
			<tr>
                <td>
                    <b><?=$adv_11n_preferred?></b><br>
                    <?=$adv_11n_preferred_msg?>
                </td>
            </tr>
<? if(query("/runtime/web/display/agingout")!="1") {echo "-->";}?>
    <? if(query("/runtime/web/display/utilization") =="0")  {echo "<!--";} ?>
            <tr>
                <td>
                    <b><?=$adv_network_utilization?></b><br>
                    <?=$adv_network_utilization_msg?>
                </td>
            </tr>
	<? if(query("/runtime/web/display/utilization") =="0")  {echo "-->";} ?>
<? if(query("/runtime/web/display/agingout")!="1") {echo "<!--";}?>
			<tr>
                <td>
                    <b><?=$adv_aging_out?></b><br>
                    <?=$adv_aging_out_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_rssi_thr?></b><br>
                    <?=$adv_rssi_thr_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_data_rate_thr?></b><br>
                    <?=$adv_data_rate_thr_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_acl_rssi?></b><br>
                    <?=$adv_acl_rssi_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_acl_rssi_thr?></b><br>
                    <?=$adv_acl_rssi_thr_msg?>
                </td>
            </tr>
<? if(query("/runtime/web/display/agingout")!="1") {echo "-->";}?>
			<tr>
				<td class="help_title_td"><?=$title_adv_mssid?><a name="adv_mssid"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_mssid_msg?></td>
			</tr>
			<tr>
				<td><?=$adv_mssid_msg1?></td>
			</tr>
			<!--<tr>
				<td><?=$adv_mssid_msg2?></td>
			</tr>
			<tr>
				<td><?=$adv_mssid_msg3?></td>
			</tr>
			<tr>
				<td><?=$adv_mssid_msg4?></td>
			</tr>
			<tr>
				<td><?=$adv_mssid_msg5?></td>
			</tr>-->
			<tr>
                <td><?=$adv_mssid_msg6?></td>
            </tr>
            <tr>
			<tr>
				<td class="help_title_td"><?=$title_adv_vlan?><a name="adv_8021q"><a name="adv_8021q_s"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_vlan_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_adv_intrusion?><a name="adv_rogue"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_intrusion_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_adv_scheduling?><a name="adv_schedule"><a name="adv_schedule_s"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_scheduling_msg?></td>
			</tr>
			<!--tr>
				<td class="help_title_td"><?=$title_adv_ap_array?><a name="adv_ap_array"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_ap_array_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_enable_array?></b><br>
					<?=$adv_enable_array_msg?>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_ap_array_name?></b><br>
					<?=$adv_ap_array_name_msg?>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_ap_array_pwd?></b><br>
					<?=$adv_ap_array_pwd_msg?>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_scan_ap_array_list?></b><br>
					<?=$adv_scan_ap_array_list_msg?>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_ap_array_list?></b><br>
					<?=$adv_ap_array_list_msg?>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_current_array_members?></b><br>
					<?=$adv_current_array_members_msg?>
				</td>	
			</tr>
			<tr>
                <td>
                    <b><?=$adv_syn_parameters?></b><br>
                    <?=$adv_syn_parameters_msg?>
                </td>
            </tr-->

<? if(query("/runtime/web/display/url_redir")!="1") {echo "<!--";}?>
					<tr>
                <td class="help_title_td"><?=$title_adv_url?><a name="adv_url_addr"></a></td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_enable_web?></b><br>
                    <?=$adv_enable_web_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$adv_web_site?></b><br>
                    <?=$adv_web_site_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$adv_enable_auth?></b><br>
                    <?=$adv_enable_auth_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$adv_url_username?></b><br>
                    <?=$adv_url_username_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$adv_url_password?></b><br>
                    <?=$adv_url_password_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$adv_url_status?></b><br>
                    <?=$adv_url_status_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$adv_url_account_list?></b><br>
                    <?=$adv_url_account_list_msg?>
                </td>
            </tr>
<? if(query("/runtime/web/display/url_redir")!="1") {echo "-->";}?>
			<tr>
				<td class="help_title_td"><?=$title_adv_int_radius_server?><a name="adv_radiusserver"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_int_radius_server_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_user_name?></b><br>
					<?=$adv_user_name_msg?>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_pwd?></b><br>
					<?=$adv_pwd_msg?>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_status?></b><br>
					<?=$adv_status_msg?>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_radius_account_list?></b><br>
					<?=$adv_radius_account_list_msg?>
				</td>	
			</tr>
			<tr>
                <td class="help_title_td"><?=$title_adv_arp_spoofing?><a name="adv_arpspoofing"></a></td>
            </tr>
            <tr>
                <td><?=$title_adv_arp_spoofing_msg?></td>
            </tr>
            <tr>
                <td>
                    <b><?=$adv_arp_spoofing?></b><br>
                    <?=$adv_arp_spoofing_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_gateway_ip?></b><br>
                    <?=$adv_gateway_ip_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_gateway_mac?></b><br>
                    <?=$adv_gateway_mac_msg?>
                </td>
            </tr>

			<tr>
				<td class="help_title_td"><?=$title_adv_fair_air_time?><a name="adv_fair"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_fair_air_time_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_downlink_and_uplink_bandwidth?></b><br>
					<?=$adv_downlink_and_uplink_bandwidth_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_add_fair_air_time_rule?></b><br>
					<?=$adv_add_fair_air_time_rule_msg?>
				</td>
			</tr>
			<tr>
                <td>
                    <b><?=$adv_rule_type?></b><br>
                    <?=$adv_rule_type_msg1?><br>
					<?=$adv_rule_type_msg2?><br>
					<?=$adv_rule_type_msg3?><br>
					<?=$adv_rule_type_msg4?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_fair_air_time_band?></b><br>
                    <?=$adv_fair_air_time_band_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_fair_air_time_ssid?></b><br>
                    <?=$adv_fair_air_time_ssid_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_downlink_speed?></b><br>
                    <?=$adv_downlink_speed_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$adv_uplink_speed?></b><br>
                    <?=$adv_uplink_speed_msg?>
                </td>
            </tr>
		<!--<tr>
				<td class="help_title_td"><?=$title_adv_qos?><a name="adv_qos"></a></td>
			</tr>
			<tr>
				<td><?=$title_adv_qos_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_enable_qoS?></b><br>
					<?=$adv_enable_qoS_msg?><br>	
					<?=$adv_enable_qoS_msg1?>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_http?></b><br>
					<?=$adv_http_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_automatic?></b><br>
					<?=$adv_automatic_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_qos_rule?></b><br>
					<?=$adv_qos_rule_msg?>	
				</td>	
			</tr>
			<tr>
				<td><?=$adv_qos_rule_msg1?></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_name?></b><br>
					<?=$adv_name_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_priority?></b><br>
					<?=$adv_priority_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$adv_priority_msg1?><br>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$adv_priority_msg2?><br>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$adv_priority_msg3?><br>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$adv_priority_msg4?><br>
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_protocol?></b><br>
					<?=$adv_protocol_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_host_1_ip?></b><br>
					<?=$adv_host_1_ip_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_host_1_port?></b><br>
					<?=$adv_host_1_port_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_host_2_ip?></b><br>
					<?=$adv_host_2_ip_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$adv_host_2_port?></b><br>
					<?=$adv_host_2_port_msg?>	
				</td>	
			</tr>-->
		</table>

		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_ap_array?></td>
			</tr>
		</table>
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">
			<tr>
				<td><?=$head_ap_array_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_array_scan?><a name="adv_array_scan"></a></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_array_enable?></b><br>
					<?=$adv_array_enable_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_array_name?></b><br>
					<?=$adv_array_name_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_array_password?></b><br>
					<?=$adv_array_password_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_array_scan?></b><br>
					<?=$adv_array_scan_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_array_list?></b><br>
					<?=$adv_array_list_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_array_current?></b><br>
					<?=$adv_array_current_msg?>
				</td>
			</tr>

			<tr>
				<td class="help_title_td"><?=$title_array_config?><a name="adv_array_config"></a></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_enbale_config?></b><br>
					<?=$adv_enbale_config_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_array_clear?></b><br>
					<?=$adv_array_clear_msg?>
				</td>
			</tr>
			
			<tr>
				<td class="help_title_td"><?=$title_auto_rf?><a name="adv_auto_rf"></a></td>
			</tr>
			<tr>
				<td><?=$title_auto_rf_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_enable_autorf?></b><br>
					<?=$adv_enable_autorf_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_init_autorf?></b><br>
					<?=$adv_init_autorf_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_auto_init?></b><br>
					<?=$adv_auto_init_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_auto_period?></b><br>
					<?=$adv_auto_period_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_auto_rssi?></b><br>
					<?=$adv_auto_rssi_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_report_freq?></b><br>
					<?=$adv_report_freq_msg?>
				</td>
			</tr>
			<!--tr>
				<td>
					<b><?=$adv_auto_miss?></b><br>
					<?=$adv_auto_miss_msg?>
				</td>
			</tr-->

			<tr>
				<td class="help_title_td"><?=$title_balance?><a name="adv_load_balance"></a></td>
			</tr>
			<tr>
				<td><?=$title_balance_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_balance_enable?></b><br>
					<?=$adv_balance_enable_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_balance_thre?></b><br>
					<?=$adv_balance_thre_msg?>
				</td>
			</tr>
		</table>

			<table id="table_header" cellspacing="0" cellpadding="0">
				<tr>
					<td id="td_header"><?=$head_captive?></td>
				</tr>
			</table>
			<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">
				<tr>
					<td><?=$head_captive_msg?></td>
				</tr>
				<tr>
					<td class="help_title_td"><?=$title_authentication?><a name="adv_captivals"><a name="adv_captivals_v2"></a></td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_encryption_type?></b><br>
						<?=$adv_encryption_type_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_captive_add?></b><br>
						<?=$adv_captive_add_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_web_redirect?></b><br>
						<?=$adv_web_redirect_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_url_path?></b><br>
						<?=$adv_url_path_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_ticket?></b><br>
						<?=$adv_ticket_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_quantity?></b><br>
						<?=$adv_quantity_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_duration?></b><br>
						<?=$adv_duration_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_last_active_day?></b><br>
						<?=$adv_last_active_day_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_ticket_user_limit?></b><br>
						<?=$adv_ticket_user_limit_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_local?></b><br>
						<?=$adv_local_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_local_username?></b><br>
						<?=$adv_local_username_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_local_password?></b><br>
						<?=$adv_local_password_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_remote_radius?></b><br>
						<?=$adv_remote_radius_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_type?></b><br>
						<?=$adv_type_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_radius_server?></b><br>
						<?=$adv_radius_server_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_radius_port?></b><br>
						<?=$adv_radius_port_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_radius_secret?></b><br>
						<?=$adv_radius_secrett_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_ldap?></b><br>
						<?=$adv_ldap_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_ldap_server?></b><br>
						<?=$adv_ldap_server_msg?>
					</td>
				</tr>
				<tr>
				<td>
					<b><?=$adv_ldap_port?></b><br>
					<?=$adv_ldap_port_msg?>
				</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_ldap_mode?></b><br>
						<?=$adv_ldap_mode_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_ldap_username?></b><br>
						<?=$adv_ldap_username_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_ldap_password?></b><br>
						<?=$adv_ldap_password_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_basedn?></b><br>
						<?=$adv_basedn_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_account?></b><br>
						<?=$adv_account_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_identity?></b><br>
						<?=$adv_identity_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_auto_copy?></b><br>
						<?=$adv_auto_copy_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_pop3?></b><br>
						<?=$adv_pop3_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_pop3_server?></b><br>
						<?=$adv_pop3_server_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_pop3_port?></b><br>
						<?=$adv_pop3_port_msg?>
					</td>
				</tr>
				<tr>
					<td>
						<b><?=$adv_connection_type?></b><br>
						<?=$adv_connection_type_msg?>
					</td>
				</tr>

			<tr>
				<td class="help_title_td"><?=$title_login_upload?><a name="adv_captivalu_v2"></a></td>
			</tr>
			<tr>
				<td><?=$title_login_upload_msg?></td>
			</tr>
			
			<tr>
				<td class="help_title_td"><?=$title_ipfilter?><a name="adv_ip_filter"></a></td>
			</tr>
			<tr>
				<td><?=$title_ipfilter_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$ipfilter_ip_address?></b><br>
					<?=$ipfilter_ip_address_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$ipfilter_ip_mask?></b><br>
					<?=$ipfilter_ip_mask_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$ipfilter_upload_download?></b><br>
					<?=$ipfilter_upload_download_msg?>
				</td>
			</tr>
			
			<tr>
				<td class="help_title_td"><?=$title_macbypass?><a name="adv_macbypass"></a></td>
			</tr>
			<tr>
				<td><?=$title_macbypass_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$macbypass_mac?></b><br>
					<?=$macbypass_mac_msg?>
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$macbypass_upload_download?></b><br>
					<?=$macbypass_upload_download_msg?>
				</td>
			</tr>
		</table>

		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_dhcp?></td>
			</tr>	
		</table>		
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td><?=$head_dhcp_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_dhcp_dynamic_pool?><a name="adv_dhcpd"></a></td>
			</tr>
			<tr>
				<td><?=$title_dhcp_dynamic_pool_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_ip_assigned?></b><br>
					<?=$dhcp_ip_assigned_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_range_of_pool?></b><br>
					<?=$dhcp_range_of_pool_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_submask?></b><br>
					<?=$dhcp_submask_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_gateway?></b><br>
					<?=$dhcp_gateway_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_wins?></b><br>
					<?=$dhcp_wins_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_dns?></b><br>
					<?=$dhcp_dns_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_domain?></b><br>
					<?=$dhcp_domain_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_lease_time?></b><br>
					<?=$dhcp_lease_time_msg?>	
				</td>	
			</tr>					
			<tr>
				<td class="help_title_td"><?=$title_dhcp_static_pool?><a name="adv_dhcps"></a></td>
			</tr>
			<tr>
				<td><?=$title_dhcp_static_pool_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_assigned_ip?></b><br>
					<?=$dhcp_assigned_ip_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_assigned_mac?></b><br>
					<?=$dhcp_assigned_mac_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_submask?></b><br>
					<?=$dhcp_submask_static_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_gateway?></b><br>
					<?=$dhcp_gateway_static_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_wins?></b><br>
					<?=$dhcp_wins_static_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_dns?></b><br>
					<?=$dhcp_dns_static_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$dhcp_domain?></b><br>
					<?=$dhcp_domain_static_msg?>	
				</td>	
			</tr>
			
			<tr>
				<td class="help_title_td"><?=$title_dhcp_current_ip?><a name="adv_dhcpl"></a></td>
			</tr>
			<tr>
				<td><?=$title_dhcp_current_ip_msg?></td>
			</tr>
		</table>
		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_filters?></td>
			</tr>	
		</table>		
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td><?=$head_filters_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_filters_wireless_access?><a name="adv_acl"><a name="adv_acl_s"><a name="adv_acl_perssid"></a></td>
			</tr>
			<tr>
				<td>
					<b><?=$filters_wireless_band?></b><br>
					<?=$filters_wireless_band_msg?>	
				</td>	
			</tr>
			<tr>
                <td>
                    <b><?=$filters_acl_mac?></b><br>
                    <?=$filters_acl_mac_msg?>
                </td>
            </tr>
			<tr>
                <td>
                    <b><?=$filters_acl_upload_download?></b><br>
                    <?=$filters_acl_upload_download_msg?>
                </td>
            </tr>
			<tr>
				<td class="help_title_td"><?=$title_filters_wlan_partition?><a name="adv_partition"></a></td>
			</tr>
			<tr>
				<td>
					<b><?=$adv_link_integrality?></b><br>
					<?=$adv_link_integrality_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$filters_internal_station?></b><br>
					<?=$filters_internal_station2_msg?>	
				</td>	
			</tr>
			<tr>
                <td>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$filters_internal_station2_msg1?><br>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$filters_internal_station2_msg2?><br>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$filters_internal_station2_msg3?><br>
                </td>
            </tr>
			<tr>
				<td>
					<b><?=$filters_eth_to_wlan?></b><br>
					<?=$filters_eth_to_wlan_msg?>	
				</td>	
			</tr>
		</table>
		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_traffic_control?></td>
			</tr>	
		</table>		
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td><?=$head_traffic_control_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_traffic_updownlink_st?><a name="adv_updnsetting"><a name="adv_updnsetting_s"></a></td>
			</tr>
			<tr>
				<td><?=$title_traffic_updownlink_st_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_traffic_qos?><a name="adv_qos_user"></a></td>
			</tr>
			<tr>
				<td><?=$title_traffic_qos_msg?></td>
			</tr>
			<tr>
                <td>
                    <b><?=$adv_priority?></b><br>
                    <?=$adv_priority2_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$adv_priority2_msg1?><br>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$adv_priority2_msg2?><br>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$adv_priority2_msg3?><br>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$adv_priority2_msg4?><br>
                </td>
            </tr>
			<tr>
				<td>
					<b><?=$traffic_qos_enable?></b><br>
					<?=$traffic_qos_enable_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_qos_down_banwidth?></b><br>
					<?=$traffic_qos_down_banwidth_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_qos_up_banwidth?></b><br>
					<?=$traffic_qos_up_banwidth_msg?>	
				</td>	
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_traffic_manager?><a name="adv_trafficmanage"></a></td>
			</tr>
			<tr>
				<td><?=$title_traffic_manager_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$traffic_traffic_manager?></b><br>
					<?=$traffic_traffic_manager_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_unlisted_clients_traffic?></b><br>
					<?=$traffic_unlisted_clients_traffic_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_down_bandwidth?></b><br>
					<?=$traffic_down_bandwidth_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_up_bandwidth?></b><br>
					<?=$traffic_up_bandwidth_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_name?></b><br>
					<?=$traffic_name_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_client_ip?></b><br>
					<?=$traffic_client_ip_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_client_mac?></b><br>
					<?=$traffic_client_mac_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_down_speed?></b><br>
					<?=$traffic_down_speed_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$traffic_up_speed?></b><br>
					<?=$traffic_up_speed_msg?>	
				</td>	
			</tr>
		</table>
		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_st?></td>
			</tr>	
		</table>
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td class="help_title_td"><?=$title_st_dev_info?><a name="st_device"></a></td>
			</tr>
			<tr>
				<td><?=$title_st_dev_info_msg?></td>
			</tr>			
			<tr>
				<td class="help_title_td"><?=$title_st_cli_info?><a name="st_info"></a></td>
			</tr>
			<tr>
				<td><?=$title_st_cli_info_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_st_wds_info?><a name="st_wds_info"></a></td>
			</tr>
			<tr>
				<td><?=$title_st_wds_info_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_chan_analyze?><a name="st_ap"></a></td>
			</tr>
			<tr>
				<td><?=$title_chan_analyze_msg?></td>
			</tr>
		</table>
		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_statistics?></td>
			</tr>	
		</table>
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td class="help_title_td"><?=$title_st_ethernet?><a name="st_stats_lan"></a></td>
			</tr>
			<tr>
				<td><?=$title_st_ethernet_msg?></td>
			</tr>					
			<tr>
				<td class="help_title_td"><?=$title_st_wlan?><a name="st_stats_wl"></a></td>
			</tr>
			<tr>
				<td><?=$title_st_wlan_msg?></td>
			</tr>
		</table>
		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_log?></td>
			</tr>	
		</table>
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td><?=$head_log_msg?></td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_log_view?><a name="st_log"></a></td>
			</tr>
			<tr>
				<td><?=$title_log_view_msg?></td>
			</tr>			
			<tr>
				<td class="help_title_td"><?=$title_log_set?><a name="st_logs"></a></td>
			</tr>
			<tr>
				<td><?=$title_log_set_msg?></td>
			</tr>
			<tr>
                <td class="help_title_td"><?=$title_email?></td>
            </tr>
            <tr>
                <td><?=$title_email_msg?></td>
            </tr>
            <tr>
                <td class="help_title_td"><?=$title_email_schedule?></td>
            </tr>
            <tr>
                <td><?=$title_email_schedule_msg?></td>
            </tr>
		</table>
		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_mt?></td>
			</tr>	
		</table>
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td class="help_title_td"><?=$title_mt_admin?><a name="tool_admin"></a></td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_limit_admin_vid?></b><br>
					<?=$mt_limit_admin_vid_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_limit_admin_ip?></b><br>
					<?=$mt_limit_admin_ip_msg?>	
				</td>	
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_mt_sysname?></td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_sysname?></b><br>
					<?=$mt_sysname_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_location?></b><br>
					<?=$mt_location_msg?>	
				</td>	
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_mt_login?></td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_username?></b><br>
					<?=$mt_username_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_newpass?></b><br>
					<?=$mt_newpass_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_conpass?></b><br>
					<?=$mt_conpass_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_applypass?></b><br>
					<?=$mt_applypass_msg?>
				</td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_mt_console?></td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_status?></b><br>
					<?=$mt_status_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_console_protocol?></b><br>
					<?=$mt_console_protocol_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_timeout?></b><br>
					<?=$mt_timeout_msg?>	
				</td>	
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_mt_snmp?></td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_st_snmp?></b><br>
					<?=$mt_st_snmp_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_public_comm?></b><br>
					<?=$mt_public_comm_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_private_comm?></b><br>
					<?=$mt_private_comm_msg?>	
				</td>	
			</tr>
<? if(query("/runtime/web/display/snmp/trap") =="0")	{echo "<!--";} ?>			
			<tr>
				<td>
					<b><?=$mt_trap?></b><br>
					<?=$mt_trap_msg?>	
				</td>	
			</tr>
			<tr>
				<td>
					<b><?=$mt_trap_serv?></b><br>
					<?=$mt_trap_serv_msg?>	
				</td>	
			</tr>
<? if(query("/runtime/web/display/snmp/trap") =="0")	{echo "-->";} ?>	
<? if(query("/runtime/web/display/ping_control") =="0")	{echo "<!--";} ?>			
			<tr>
				<td class="help_title_td"><?=$title_mt_pingctrl?></td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_ping_st?></b><br>
					<?=$mt_ping_st_msg?>	
				</td>	
			</tr>		
<? if(query("/runtime/web/display/ping_control") =="0")	{echo "-->";} ?>				
			<tr>
				<td class="help_title_td"><?=$title_mt_wifimanager?></td>
			</tr>
			<tr>
				<td><?=$title_mt_wifimanager_msg?></td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_enbale_wifimanager?></b><br>
					<?=$mt_enbale_wifimanager_msg?>
				</td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_mt_fw?><a name="tool_fw"></a></td>
			</tr>
			<tr>
				<td>
					<b><?=$title_mt_fw_msg?></b><br>
					<?=$title_mt_fw_msg1?>	
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_upload_fw?></b><br>
					<?=$mt_upload_fw_msg?>	
				</td>	
			</tr>
<? if(query("/runtime/web/display/language") !="1") {echo "<!--";} ?>
			<tr>
                <td>
                    <b><?=$mt_upload_language?></b><br>
                    <?=$mt_upload_language_msg?>
                </td>
            </tr>
<? if(query("/runtime/web/display/language") !="1") {echo "-->";} ?>
			<tr>
				<td>
					<b><?=$mt_upload_ssl?></b><br>
					<?=$mt_upload_ssl_msg?>	
				</td>	
			</tr>					
			<tr>
				<td class="help_title_td"><?=$_title_mt_config?><a name="tool_config"></a></td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_config?></b><br>
					<?=$mt_config_msg?>	
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_upload_config?></b><br>
					<?=$mt_upload_config_msg?>	
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_download_config?></b><br>
					<?=$mt_download_config_msg?>	
				</td>
			</tr>
			<tr>
				<td>
					<b><?=$mt_upload_cwm?></b><br>
					<?=$mt_upload_cwm_msg?>
				</td>
			</tr>
			<tr>
				<td class="help_title_td"><?=$title_mt_time?><a name="tool_sntp"></a></td>
			</tr>
			<tr>
				<td>
					<?=$title_mt_time_msg?>	
				</td>
			</tr>
		</table>
		<table id="table_header" cellspacing="0" cellpadding="0">
            <tr>
                <td id="td_header"><?=$head_config?></td>
            </tr>
        </table>
        <table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">
            <tr>
                <td>
                    <b><?=$config_save_activate?></b><br>
                    <?=$config_save_activate_msg?>
                </td>
            </tr>
            <tr>
                <td>
                    <b><?=$config_discard_change?></b><br>
                    <?=$config_discard_change_msg?>
                </td>
            </tr>
        </table>
		<table id="table_header" cellspacing="0" cellpadding="0">
			<tr>
				<td id="td_header"><?=$head_sys?></td>
			</tr>	
		</table>
		<table id="table_set_main"  border="0"  cellspacing="5" cellpadding="5">					
			<tr>
				<td class="help_title_td"><?=$title_sys?><a name="sys_setting"></a></td>
			</tr>
			<tr>
				<td>
					<b><?=$sys_apply_restart?></b><br>
					<?=$sys_apply_restart_msg?>	
				</td>	
			</tr>	
			<tr>
				<td>
					<b><?=$sys_apply_restore?></b><br>
					<?=$sys_apply_restore_msg?>	
				</td>	
			</tr>								
<? if(query("/runtime/web/display/language") !="1") {echo "<!--";} ?>
			<tr>
                <td>
                    <b><?=$sys_clear_language?></b><br>
                    <?=$sys_clear_language_msg?>
                </td>
            </tr>
<? if(query("/runtime/web/display/language") !="1") {echo "-->";} ?>
		</table>	
	</td>
</tr>		
</table>
</center>
</form>
</body>
</html>
